function plot_curve_vs_param(param,Np1,Np2,curve,Nc1,Nc2,crve_color,ls,lw,mfc)
global m_size
plot(param(Np1:Np2),curve(Nc1:Nc2),...
    'Color',crve_color,'LineStyle',ls,...
    'LineWidth',lw,'Marker','o','MarkerSize',m_size,...
    'MarkerEdgeColor',crve_color,...
    'MarkerFaceColor',mfc); hold on;
end