//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Spcord.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_LOCOTYPE                    129
#define IDR_NSMFRAME                    130
#define IDR_NSMTYPE                     131
#define IDR_LIMBVIEW                    132
#define IDD_DRIVE_NAME                  179
#define IDD_FEEDBACK_PROP               186
#define IDD_MEASURES_PROP               188
#define IDD_CONNECT_SOURCE_SETUP        193
#define IDD_OUTPUT_PROP                 206
#define IDD_CONTROL_FUNCTION            207
#define IDD_PROP_POINT                  208
#define IDD_NETWORK_VIEW                210
#define IDD_SCALE_VIEW                  211
#define IDD_GEOMETRY_VIEW               212
#define IDD_SAVE_RESULTS                225
#define IDD_POPULAT_SETUP               230
#define IDD_NN_UNIT_SEL                 231
#define IDB_TREE_IMAGES                 232
#define IDD_WEIGHTS                     233
#define IDD_DRIVE_SETUP                 234
#define IDD_OUTPUT_SETUP                235
#define IDD_FEEDBACK_SETUP              236
#define IDD_CONTROL_SETUP               237
#define IDD_PAR_SEL                     238
#define IDD_WEIGHTS_RESP                239
#define ID_WEIGHT_DEP                   240
#define IDD_NETWORK_PARAMETERS          249
#define IDD_CONTROLLED_SETUP            250
#define IDD_SIMULATE_VIEW               251
#define IDD_SIMULATE_LIMB               252
#define IDD_CONNECT_TARGET_SETUP        253
#define IDD_BIOMECH_PARAMETERS          254
#define IDD_POPULAT_PROPERTIES          255
#define IDD_IMAGE_SIZE                  256
#define IDD_NSM_SIMULATE_PARAM          257
#define IDD_WEIGHT_DEP                  258
#define IDD_NETWORK_DIFF                259
#define IDC_EDIT_OUTPUT_NAME            1006
#define IDC_EDIT_T1                     1007
#define IDC_EDIT_T2                     1008
#define IDC_SPIN_T1                     1009
#define IDC_SPIN_T2                     1010
#define IDC_FEEDBACK_SIZE               1011
#define IDC_EDIT_THRESHOLD              1012
#define IDC_LIST_CONTROL                1013
#define IDC_SPIN_THRESHOLD              1014
#define IDC_ADD_CONTROL                 1015
#define IDC_DEL_CONTROL                 1016
#define IDC_PROP_CONTROL                1017
#define IDC_CONTROL_SIZE                1022
#define IDC_SET_CONTROLLED              1023
#define IDC_LIST_POINTS                 1026
#define IDC_LIST_VIEW                   1027
#define IDC_ADD_POINT                   1028
#define IDC_DEL_POINT                   1029
#define IDC_PROP_POINT                  1030
#define IDC_LOAD                        1031
#define IDC_EDIT_TIME                   1032
#define IDC_SAVE                        1032
#define IDC_SPIN_TIME                   1033
#define IDC_EDIT_MUL                    1034
#define IDC_SPIN_MUL                    1035
#define IDC_VIEW_TREE                   1041
#define IDC_ADD_VIEW                    1043
#define IDC_REMOVE_VIEW                 1044
#define IDC_EDIT_YMAX                   1045
#define IDC_SCALE_VIEW                  1046
#define IDC_SPIN_YMAX                   1047
#define IDC_SPIN_YMIN                   1048
#define IDC_MOVE_UP                     1049
#define IDC_GEOMETRY_VIEW               1050
#define IDC_MOVE_DOWN                   1051
#define IDC_EDIT_YMIN                   1052
#define IDC_SPIN_PV                     1077
#define IDC_SPIN_KV                     1079
#define IDC_SPIN_KF                     1080
#define IDC_SPIN_KL                     1081
#define IDC_SPIN_KC                     1082
#define IDC_SPIN_KGR                    1083
#define IDC_SPIN_KEMG                   1084
#define IDC_SPIN_KF2                    1085
#define IDC_SPIN_KFTR                   1085
#define IDC_DRIVE_NAME                  1092
#define IDC_EDIT_NAME_CTR               1102
#define IDC_ADD_NOISE                   1114
#define IDC_FB_NAME                     1115
#define IDC_COMBO_TYPE                  1116
#define IDC_KV                          1117
#define IDC_PV                          1118
#define IDC_KF                          1119
#define IDC_KL                          1120
#define IDC_KC                          1121
#define IDC_KGR                         1122
#define IDC_KEMG                        1123
#define IDC_KFTR                        1124
#define IDC_COMBO_LISTFB                1125
#define IDC_COMBO_TYPE2                 1125
#define IDC_EDIT_BV                     1151
#define IDC_SPIN_BV                     1152
#define IDC_SPIN_ANGLE_G2               1153
#define IDC_COMBO_LINK                  1154
#define IDC_EDIT_BA                     1155
#define IDC_SPIN_BA                     1157
#define IDC_EDIT_KA                     1158
#define IDC_SPIN_KA                     1159
#define IDC_EDIT_BH                     1160
#define IDC_SPIN_BH                     1161
#define IDC_EDIT_KH                     1162
#define IDC_LIST_TARGETS                1163
#define IDC_SPIN_KH                     1164
#define IDC_EDIT_SOURCE                 1165
#define IDC_EDIT_BG                     1166
#define IDC_COMBO_SOURCES               1167
#define IDC_SPIN_BG                     1168
#define IDC_ADD                         1169
#define IDC_EDIT_KG                     1170
#define IDC_DELETE                      1171
#define IDC_SPIN_KG                     1172
#define IDC_WEIGHTS                     1173
#define IDC_CONTROLLED_TREE             1174
#define IDC_EDIT_LENGTH                 1175
#define IDC_CONTROLLED_PARAM            1176
#define IDC_SPIN_LENGTH                 1177
#define IDC_ADD_PARAM                   1178
#define IDC_EDIT_MASS                   1179
#define IDC_REMOVE_PARAM                1180
#define IDC_SPIN_MASS                   1181
#define IDC_EDIT_CENTER                 1183
#define IDC_SPIN_CENTER                 1184
#define IDC_LIST_USED_TARGETS           1185
#define IDC_EDIT_INERTIA                1186
#define IDC_LIST_ALL_SOURCES            1187
#define IDC_SPIN_INERTIA                1189
#define IDC_LIST_SOURCES                1190
#define IDC_CHECK_SIMPLE                1191
#define IDC_EDIT_TARGET                 1192
#define IDC_COMBO_TARGETS               1193
#define IDC_CONNECT_TYPE                1216
#define IDC_EDIT_SIM_TIME               1217
#define IDC_SPIN_SIM_TIME               1218
#define IDC_EDIT_SIM_NN_STEP            1219
#define IDC_SPIN_SIM_NN_STEP            1220
#define IDC_EDIT_SIM_LIMB_SKIP          1223
#define IDC_SPIN_SIM_LIMB_SKIP          1224
#define IDC_EDIT_BEGIN_VIEW             1225
#define IDC_SPIN_BEGIN_VIEW             1226
#define IDC_EDIT_END_VIEW               1227
#define IDC_SPIN_END_VIEW               1228
#define IDC_EDIT_UPDATE_TIME            1229
#define IDC_SPIN_UPDATE_TIME            1230
#define IDC_CHECK_ALL_VIEWS             1231
#define IDC_EDIT_TIME_FACTOR            1234
#define IDC_SPIN_TIME_FACTOR            1235
#define IDC_EDIT_LIMB_SCALE             1236
#define IDC_SPIN_LIMB_SCALE             1237
#define IDC_EDIT_WIDTH                  1238
#define IDC_EDIT_LIMB_ORIGIN_X          1239
#define IDC_SPIN_WIDTH                  1240
#define IDC_SPIN_LIMB_ORIGIN_X          1241
#define IDC_EDIT_HIST_BIN               1242
#define IDC_EDIT_HEIGHT                 1243
#define IDC_EDIT_LIMB_ORIGIN_Y          1244
#define IDC_SPIN_HIST_BIN               1245
#define IDC_SPIN_HEIGHT                 1246
#define IDC_SPIN_LIMB_ORIGIN_Y          1247
#define IDC_EDIT_HIST_NORM              1248
#define IDC_SPIN_HIST_NORM              1249
#define IDC_COMBO_FORMAT                1250
#define IDC_DATA_LIST                   1251
#define IDC_EDIT_NUMDATA                1252
#define IDC_BUTTON_SELECTALL            1253
#define IDC_BUTTON_UNSELECTALL          1254
#define IDC_SYNAPSES_PROP               1270
#define IDC_EX_SPEC                     1271
#define IDC_EX2_SPEC                    1272
#define IDC_EDIT_NOISE                  1273
#define IDC_EDIT_VIEW_NAME              1274
#define IDC_INH1_SPEC                   1275
#define IDC_INH2_SPEC                   1276
#define IDC_BIOMECH_PROP                1277
#define IDC_CHECK_CLONE                 1277
#define IDC_SRC_CLONE                   1281
#define IDC_TRG_CLONE                   1282
#define IDC_CHAINED                     1282
#define IDC_EDIT1                       1283
#define IDC_EDIT_NETDIFF                1283
#define IDC_EDIT_DATA_WND1              1283
#define IDC_EDIT_DATA_WND2              1284
#define IDC_COMBO1                      1284
#define IDC_NUM_THREADS                 1284
#define IDC_CHECK1                      1285
#define IDC_CRL_ITERPOL                 1285
#define IDC_EDIT_TIMECNST               2015
#define IDC_LIST_POPULAT                2041
#define IDC_ADD_POPULAT                 2044
#define IDC_DEL_POPULAT                 2047
#define IDC_PROP_POPULAT                2049
#define IDC_LIST_USED_SOURCES           2073
#define IDC_LIST_ALL_TARGETS            2074
#define IDC_TAG_SEL                     2085
#define IDC_NETWORK_SIZE                2088
#define IDC_EDIT_EX_WEIGHT              2092
#define IDC_EDIT_INH1_WEIGHT            2093
#define IDC_SPIN_EX_WEIGHT              2094
#define IDC_SPIN_INH1_WEIGHT            2095
#define IDC_EDIT_EX_WEIGHT_VAR          2096
#define IDC_EDIT_EX_WEIGHT2             2097
#define IDC_SPIN_EX_WEIGHT_VAR          2098
#define IDC_SPIN_INH1_WEIGHT_VAR        2099
#define IDC_EDIT_INH2_WEIGHT            2100
#define IDC_SPIN_EX_WEIGHT2             2101
#define IDC_SPIN_INH2_WEIGHT            2102
#define IDC_EDIT_INH2_WEIGHT_VAR        2103
#define IDC_SPIN_INH2_WEIGHT_VAR        2104
#define IDC_EDIT_EX_WEIGHT_VAR2         2105
#define IDC_SPIN_EX_WEIGHT_VAR2         2106
#define IDC_GRID                        2127
#define IDC_DRIVE_SIZE                  2146
#define IDC_LIST_DRIVE                  2147
#define IDC_ADD_DRIVE                   2148
#define IDC_DEL_DRIVE                   2149
#define IDC_PROP_DRIVE                  2150
#define IDC_OUTPUT_SIZE                 2152
#define IDC_LIST_OUTPUT                 2153
#define IDC_ADD_OUTPUT                  2154
#define IDC_DEL_OUTPUT                  2155
#define IDC_PROP_OUTPUT                 2156
#define IDC_LIST_FEEDBACK               2162
#define IDC_ADD_FEEDBACK                2163
#define IDC_DEL_FEEDBACK                2164
#define IDC_PROP_FEEDBACK               2165
#define IDC_PAR_SEL                     2167
#define IDC_EDIT_ROW                    2168
#define IDC_SPIN_ROW                    2169
#define IDC_EDIT_COL                    2170
#define IDC_SPIN_COL                    2171
#define IDC_EDIT_INH1_WEIGHT_VAR        2185
#define IDC_EDIT_PROBABILITY            2186
#define IDC_SPIN_PROBABILITY            2187
#define IDM_NEW_LIMB_WINDOW             2771
#define IDM_REFRESH                     2774
#define ID_NETWORK_SETUP                2797
#define ID_NETWORK_INIT                 2800
#define ID_NETWORK_DIFF                 2801
#define ID_MODEL_START                  2802
#define ID_MODEL_STOP                   2803
#define ID_MODEL_PARAM                  2805
#define ID_MODEL_PAUSE                  2806
#define ID_NETWORK_CONTROL              2807
#define ID_ADD_NNVIEW                   2809
#define ID_NETWORK_VIEW                 2810
#define ID_LIMB_VIEW                    2811
#define ID_IS_STICK                     2816
#define ID_REDRAW_RESULTS               2817
#define ID_SAVE_RESULTS                 2825
#define ID_CONNECTION_SETUP             2831
#define ID_SAVE_VIEW                    2832
#define ID_Menu                         2833
#define ID_BIOMECHANICS                 2840

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        261
#define _APS_NEXT_COMMAND_VALUE         32842
#define _APS_NEXT_CONTROL_VALUE         1286
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
